---

- name: Configure Calico networking
  ansible.builtin.shell: |
    kubectl apply \
      -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml \
      --kubeconfig=/etc/kubernetes/admin.conf \
        > /tmp/calico.log 2>&1
  changed_when: False
