---

- name: geerlingguy.docker
  version: 6.1.0

- name: geerlingguy.containerd
  version: 1.3.1

- name: andrewrothstein.etcd
  version: v2.3.1

- name: andrewrothstein.cfssl
  version: v3.1.1

- name: ansible-etcd-cluster
  scm: git
  version: 0.1.0
  src: https://github.com/cloud-labs-infra/ansible-etcd-cluster.git

- name: ansible-etcd-cluster-certificates
  scm: git
  version: 0.2.0
  src: https://github.com/cloud-labs-infra/ansible-etcd-cluster-certificates.git
