---

roles:
  - name: geerlingguy.containerd
    version: 1.3.1

  - name: geerlingguy.haproxy
    version: 1.3.1

  - name: andrewrothstein.etcd
    version: v2.3.1

  - name: andrewrothstein.cfssl
    version: v3.1.1

  - name: cloudlabsinfra.etcd_cluster
    version: v1.0.0

  - name: cloudlabsinfra.etcd_cluster_certificates
    version: v1.0.0

collections:
  - name: community.general
    version: 7.0.1

  - name: community.docker
    version: 3.4.8
