# tasks/configure-masters.yml
---

- name: Initialize cluster on main control-plane node
  ansible.builtin.include_tasks: init-control-plane.yml
  when:
    - k8s_cluster_initial_master | bool
    - services_state.ansible_facts.services['kubelet.service'].state != "running"

- name: Prepare environment to join other nodes
  ansible.builtin.include_tasks: set-join-environment.yml
  when: k8s_cluster_initial_master | bool

- name: Join other control-plane nodes
  ansible.builtin.include_tasks: join-node.yml
  when:
    - not k8s_cluster_initial_master | bool
    - services_state.ansible_facts.services['kubelet.service'].state != "running"

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/conf
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644
