---

# https://github.com/flannel-io/flannel
- name: Configure default (Flannel) networking
  ansible.builtin.shell: |
    kubectl apply \
      -f {{ k8s_cluster_flannel_apply }} \
      --kubeconfig=/etc/kubernetes/admin.conf \
        > /tmp/flannel.log 2>&1
  changed_when: False
  when:
    - k8s_cluster_custom_networking_tasks_path == ""
    - k8s_cluster_flannel_apply != ""

- name: Configure custom networking
  ansible.builtin.include_tasks: "{{ k8s_cluster_custom_networking_tasks_path }}"
  when:
    - k8s_cluster_custom_networking_tasks_path != ""
    - k8s_cluster_flannel_apply == ""
