# tasks/control-plane.yml
---

- name: Copy initial kubeadm template
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ k8s_cluster_kubelet_config_root_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0640
  loop: ["kubeadm-init-config.yml"]

- name: Pre pull required images
  ansible.builtin.shell: |
    kubeadm config images pull
  changed_when: False

- name: Initialize cluster on control-plane nodes
  ansible.builtin.include_tasks: init-control-plane.yml
  when: k8s_cluster_initial_master | bool

- name: Join additional control-plane
  ansible.builtin.include_tasks: join-control-plane.yml
  when: not k8s_cluster_initial_master | bool

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/conf
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644

# https://github.com/flannel-io/flannel
- name: Configure Flannel networking
  ansible.builtin.shell: |
    kubectl apply -f {{ k8s_cluster_flannel_apply }} > /tmp/flannel.log 2>&1
  changed_when: False
  when: k8s_cluster_initial_master | bool
