# tasks/join-node.yml
---

- name: Copy initial kubeadm template
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ k8s_cluster_kubelet_config_root_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0640
  loop: ["kubeadm-join-config.yml"]

- name: Join node to cluster
  ansible.builtin.shell: |
    kubeadm join \
      --config={{ k8s_cluster_kubelet_config_root_dir }}/kubeadm-join-config.yml \
        > /tmp/join.log 2>&1
  changed_when: false

- name: Check nodes until ready
  ansible.builtin.shell: |
    kubectl get node {{ k8s_cluster_node_name }} \
      --kubeconfig=/etc/kubernetes/admin.conf -o json | jq -Mr '.status.conditions[4].status'
  register: kubectl_response
  changed_when: false
  delegate_to: "{{ k8s_cluster_init_main_node_hostname }}"
  until: kubectl_response.stdout == "True"
  retries: 48
  delay: 5
