---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - &default_platform
    name: k8s-control-plane-01
    hostname: k8s-control-plane-01
    image: k8s-temp:latest
    groups:
      - control_plane
    volumes:
      - /lib/modules:/lib/modules:ro
      - /var/lib/containerd
    privileged: true
    pre_build_image: true
    sysctls:
      net.bridge.bridge-nf-call-iptables: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.ipv4.ip_forward: 1
  - <<: *default_platform
    name: k8s-worker-01
    hostname: k8s-worker-01
    groups:
      - workers
provisioner:
  name: ansible
