---

- name: Configure host
  hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: Set proper nf_conntrack_max
      ansible.posix.sysctl:
        name: net.netfilter.nf_conntrack_max
        value: '393216'
        sysctl_set: true
        state: present
        reload: true

- name: Configure k8s instances
  hosts:
    - control_plane
    - workers
  gather_facts: false
  tasks:
    - name: Install Python
      ansible.builtin.raw: apt update && apt install -y python3-pip python3 python3-apt
      changed_when: false
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
          - kmod  # modprobe and lsmod
          - net-tools
          - curl
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:

- name: Configure certs
  hosts:
    - etcd
    - etcd_clients
  gather_facts: false
  become_method: su
  vars:
    # cloudlabsinfra.etcd_cluster_certificates role related variables
    etcd_cert_dir: /etc/ssl/private
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2 # provides network facts
          - net-tools
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  roles:
    - { role: andrewrothstein.cfssl }
    - { role: ansible-etcd-cluster-certificates }

- name: Configure etcd
  hosts: etcd
  become: yes
  gather_facts: false
  roles:
    - { role: andrewrothstein.etcd }
    - { role: cloudlabsinfra.etcd_cluster }




- name: Converge
  hosts: all
  become: yes
  become_method: su
  gather_facts: false
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
          - kmod  # modprobe and lsmod
          - net-tools
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  tasks:
    - name: "Include cloudlabsinfra.k8s_cluster"
      ansible.builtin.include_role:
        name: "cloudlabsinfra.k8s_cluster"
