---

- name: Verify control plane
  hosts: control_plane
  gather_facts: false
  tasks:
    - name: Include verify common
      ansible.builtin.include_tasks:
        file: ../verify-common.yml

    - name: temporary test
      ansible.builtin.shell: |
        netstat -tulpn
      register: netstat
      changed_when: false

    - name: Debug
      ansible.builtin.debug:
        var: netstat
