    - name: Install Python
      ansible.builtin.raw: apt update && apt install -y python3-pip python3 python3-apt
      changed_when: false

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
          - kmod  # modprobe and lsmod
          - net-tools
          - curl
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:

    - name: Make containerd defautl to crictl
      ansible.builtin.copy:
        content: "runtime-endpoint: unix:///var/run/containerd/containerd.sock\n"
        dest: /etc/crictl.yaml
        owner: root
        group: root
        mode: 0640
