---

- name: Configure host
  hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: Set proper nf_conntrack_max
      ansible.posix.sysctl:
        name: net.netfilter.nf_conntrack_max
        value: '393216'
        sysctl_set: true
        state: present
        reload: true

- name: Configure instances
  hosts: all
  gather_facts: false
  tasks:
    - name: Include configure for k8s instances
      ansible.builtin.include_tasks:
        file: ../configure-k8s-instances.yml

- name: Converge
  hosts: all
  become: yes
  become_method: su
  gather_facts: false
  tasks:
    - name: "Include cloudlabsinfra.k8s_cluster"
      ansible.builtin.include_role:
        name: "cloudlabsinfra.k8s_cluster"
