---

- name: Verify control plane
  hosts: control_plane
  gather_facts: false
  tasks:
    - name: Include checks for control plane
      ansible.builtin.include_tasks:
        file: ../verify-common.yml

    - name: Include kubelet checks
      ansible.builtin.include_tasks:
        file: ../verify-kubelet.yml

- name: Verify workers
  hosts: workers
  tasks:
    - name: Include checks for worker
      ansible.builtin.include_tasks:
        file: ../verify-workers.yml

    - name: Include kubelet checks
      ansible.builtin.include_tasks:
        file: ../verify-kubelet.yml
