dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance-1
    box: ubuntu/focal64
    memory: 2500
    cpus: 2
    interfaces:
      - network_name: private_network
        ip: 192.168.56.20
        guest: 80
        host: 8080
    groups: [control-plane]
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        variable1: value
        variable2: False
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: testinfra
  options:
    sudo: true
    v: 1