---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: k8s-control-plane-01
    hostname: k8s-control-plane-01
    image: kindest/node:v1.26.3
    groups:
      - etcd
      - control_plane
    volumes:
      - /lib/modules:/lib/modules:ro
      - /var/lib/containerd
    privileged: true
    pre_build_image: true
    runtime: runc
    sysctls:
      net.bridge.bridge-nf-call-iptables: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.ipv4.ip_forward: 1
provisioner:
  name: ansible
