---

- name: Configure host
  hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: Set proper nf_conntrack_max
      ansible.posix.sysctl:
        name: net.netfilter.nf_conntrack_max
        value: '393216'
        sysctl_set: true
        state: present
        reload: true

- name: Configure k8s instances
  hosts: control_plane
  gather_facts: false
  tasks:
    - name: Install Python
      ansible.builtin.raw: apt update && apt install -y python3-pip python3 python3-apt
      changed_when: false

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
          - kmod  # modprobe and lsmod
          - net-tools
          - curl
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:

- name: Configure certs
  hosts: all
  gather_facts: false
  become_method: su
  vars:
    # ansible-etcd-cluster-certificates role related variables
    etcd_cert_dir: /etc/ssl/private
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2 # provides network facts
          - net-tools
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  roles:
    - { role: andrewrothstein.cfssl }
    - { role: ansible-etcd-cluster-certificates }

- name: Configure etcd
  hosts: etcd
  become: yes
  gather_facts: false
  vars:
    # ansible-etcd-cluster-certificates role related variables
    etcd_cert_dir: /etc/ssl/private
    # ansible-etcd-cluster role related variables
    # client/server
    etcd_trusted_ca_file: "{{ etcd_conf_dir }}/ca.pem"
    etcd_key_file: "{{ etcd_conf_dir }}/server-key.pem"
    etcd_cert_file: "{{ etcd_conf_dir }}/server.pem"
    etcd_client_cert_auth: 'true'
    # peer
    etcd_peer_trusted_ca_file: "{{ etcd_trusted_ca_file }}"
    etcd_peer_key_file: "{{ etcd_conf_dir }}/peer-key.pem"
    etcd_peer_cert_file: "{{ etcd_conf_dir }}/peer.pem"
    etcd_peer_client_cert_auth: 'true'
    etcd_remote_cert_files:
      - "{{ etcd_cert_dir }}/ca.pem"
      - "{{ etcd_cert_dir }}/server-key.pem"
      - "{{ etcd_cert_dir }}/server.pem"
      - "{{ etcd_cert_dir }}/peer-key.pem"
      - "{{ etcd_cert_dir }}/peer.pem"
  roles:
    - { role: andrewrothstein.etcd }
    - { role: ansible-etcd-cluster }

- name: Converge
  hosts:
    - control_plane
    - workers
  become: yes
  become_method: su
  gather_facts: true
  vars:
    # cloudlabsinfra.k8s_cluster role related variables
    k8s_cluster_kubernetes_version: 1.26.0
    k8s_cluster_cluster_configuration:
      etcd:
        external:
          endpoints:
            - "https://{{ hostvars['etcd-instance-01']['ansible_default_ipv4']['address'] }}:2379"
          caFile: "/etc/ssl/private/ca.pem"
          certFile: "/etc/ssl/private/client.pem"
          keyFile: "/etc/ssl/private/client-key.pem"
      networking:
        serviceSubnet: 10.96.0.0/12
        podSubnet: 10.244.0.0/16
        dnsDomain: cluster.local
      kubernetesVersion: "{{ k8s_cluster_kubernetes_version }}"
      controlPlaneEndpoint: "{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}:6443"
  tasks:
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: "Include cloudlabsinfra.k8s_cluster"
      ansible.builtin.include_role:
        name: "cloudlabsinfra.k8s_cluster"
