---

- name: Converge using end-to-end
  ansible.builtin.import_playbook: ../end-to-end/converge.yml

- name: Install Helm
  hosts:
    - control_plane
  gather_facts: false
  become: true
  become_method: su
  roles:
    - { role: geerlingguy.helm }

- name: Prepare control-plane
  hosts:
    - k8s-control-plane-01
  gather_facts: false
  become: true
  become_method: su
  tasks:
    - name: Copy manifests and helm files
      ansible.builtin.copy:
        src: deploy_files/
        dest: ~/demo

    - name: Install pip library
      ansible.builtin.pip:
        name: kubernetes

- name: Nginx, Loki and Grafana deployment
  hosts:
    - k8s-control-plane-01
  gather_facts: false
  become: true
  become_method: su
  tasks:
    - name: Nginx installation
      block:
        - name: Create nginx namespace
          kubernetes.core.k8s:
            name: nginx-ns
            api_version: v1
            kind: Namespace
            state: present

        - name: Create nginx deploy
          kubernetes.core.k8s:
            state: present
            src: ~/demo/nginx/deploy.yml

        - name: Create nginx service
          kubernetes.core.k8s:
            state: present
            src: ~/demo/nginx/service.yml

    - name: Loki installation
      block:
        - name: Add grafana/loki helm repo
          kubernetes.core.helm_repository:
            name: grafana
            repo_url: "https://grafana.github.io/helm-charts"

        - name: Install loki helm release
          kubernetes.core.helm:
            name: loki
            chart_ref: grafana/loki-stack
            release_namespace: loki-ns
            create_namespace: true

    - name: Grafana installation
      block:
        - name: Install grafana helm release
          kubernetes.core.helm:
            name: grafana
            chart_ref: grafana/grafana
            release_namespace: grafana-ns
            create_namespace: true
            values_files:
              - root/demo/grafana/helm-values.yml

- name: Ingress Controller
  hosts:
    - k8s-control-plane-01
  gather_facts: false
  become: true
  become_method: su
  tasks:
    - name: Add ingress controller helm repo
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Install ingress controller helm release
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx-ns
        create_namespace: true
        values_files:
          - root/demo/ingress-controller/helm-values.yml

- name: Cert Manager
  hosts:
    - k8s-control-plane-01
  gather_facts: false
  become: true
  become_method: su
  tasks:
    - name: Install Cert Manager
      block:
        - name: Add cert-manager helm repo
          kubernetes.core.helm_repository:
            name: jetstack
            repo_url: "https://charts.jetstack.io"

        - name: Install cert-manager helm release
          kubernetes.core.helm:
            name: cert-manager
            chart_ref: jetstack/cert-manager
            release_namespace: cert-manager-ns
            create_namespace: true
            values_files:
              - root/demo/cert-manager/helm-values.yml

    - name: Prepare CA certificate
      block:
        - name: Create selfsigned issuer
          kubernetes.core.k8s:
            state: present
            src: ~/demo/cert-manager/selfsigned-issuer.yml

        - name: Create CA certificate
          kubernetes.core.k8s:
            state: present
            namespace: default
            src: ~/demo/cert-manager/selfsigned-cert.yml

        - name: Create CA issuer
          kubernetes.core.k8s:
            state: present
            src: ~/demo/cert-manager/root-ca-issuer.yml
