---

- name: Converge using end-to-end
  ansible.builtin.import_playbook: ../end-to-end/converge.yml

- name: Install Helm
  hosts:
    - control_plane
  gather_facts: false
  become: true
  become_method: su
  roles:
    - { role: geerlingguy.helm }

- name: Prepare control-plane
  hosts:
    - k8s-control-plane-01
  gather_facts: false
  become: true
  become_method: su
  tasks:
    - name: Copy manifests and helm files
      ansible.builtin.copy:
        src: deploy_files/
        dest: ~/demo

    - name: Install pip library
      ansible.builtin.pip:
        name: kubernetes

- name: Nginx, Loki and Grafana deployment
  hosts:
    - k8s-control-plane-01
  gather_facts: false
  become: true
  become_method: su
  tasks:
    - name: Nginx installation
      block:
        - name: Create nginx namespace
          kubernetes.core.k8s:
            name: nginx-ns
            api_version: v1
            kind: Namespace
            state: present

        - name: Create nginx deploy
          kubernetes.core.k8s:
            state: present
            src: ~/demo/nginx/deploy.yml

        - name: Create nginx service
          kubernetes.core.k8s:
            state: present
            src: ~/demo/nginx/service.yml

    - name: Loki installation
      block:
        - name: Add grafana/loki helm repo
          kubernetes.core.helm_repository:
            name: grafana
            repo_url: "https://grafana.github.io/helm-charts"

        - name: Install loki release
          kubernetes.core.helm:
            name: loki
            chart_ref: grafana/loki-stack
            release_namespace: loki-ns
            create_namespace: true

    - name: Grafana installation
      block:
        - name: Install grafana release
          kubernetes.core.helm:
            name: grafana
            chart_ref: grafana/grafana
            release_namespace: grafana-ns
            create_namespace: true
            values_files:
              - root/demo/grafana/helm-values.yml
