---

- name: Converge using end-to-end
  ansible.builtin.import_playbook: ../end-to-end/converge.yml

- name: Install Helm
  hosts:
    - control_plane
  gather_facts: false
  become: true
  become_method: su
  roles:
    - { role: geerlingguy.helm }
