name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-20.04
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
